name: reusable workflow
on: 
  workflow_call:
    inputs:
      build-artifacts:
        description: 'Build artifacts to deploy'
        required: true
        type: string
        default: 'dist'
    outputs:
      deploy-status:
        description: 'Status of deployment'
        value: ${{ jobs.deploy.outputs.deploy-status }}
jobs:
  deploy:
     outputs:
        deploy-status: ${{ steps.get-deploy-status.outputs.deploy-status }}
     runs-on: ubuntu-latest
     steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build-artifacts }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "called from main work flow ...Deploying..."
      - name: Set deploy status
        id: get-deploy-status
        run: echo "deploy-status=success" >> $GITHUB_OUTPUT